Fix for charts/att-comdev pipelines.
use internal funtions for initial helm setup

Change-Id: I5f2a72a6236425d51063f4540c89fd434bf2e6b9

diff --git a/charts/att-comdev/Jenkinsfile b/charts/att-comdev/Jenkinsfile
--- a/charts/att-comdev/Jenkinsfile
+++ b/charts/att-comdev/Jenkinsfile
@@ -7,8 +7,38 @@ currentBuild.displayName = "#${BUILD_NUMBER} ${GERRIT_EVENT_TYPE}"
 //bash script start:
 def build_charts = '''
 
-    #jenkins automatically adds "#!/bin/bash -xe" to the script
-    set -e
+export HELM_VERSION=${HELM_VERSION:-"v2.7.2"}
+export KUBE_VERSION=${KUBE_VERSION:-"v1.9.0"}
+
+    helm_install(){
+
+        ##Packages should already present on VM
+        #sudo apt-get install -y --no-install-recommends git make curl ca-certificates
+
+        # install helm
+        TMP_DIR="$(mktemp -d)"
+        URL="https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz"
+        curl -sSL ${URL} | tar -zxv --strip-components=1 -C ${TMP_DIR}
+        sudo mv -v ${TMP_DIR}/helm /usr/local/bin/helm
+    }
+
+    helm_serve(){
+        helm init --client-only
+        if [ -z "$(curl -s 127.0.0.1:8879 | grep 'Helm Repository')" ]; then
+            helm serve & > /dev/null
+            while [ -z "$(curl -s 127.0.0.1:8879 | grep 'Helm Repository')" ]; do
+                sleep 1
+                echo "Waiting for Helm Repository"
+            done
+        fi
+
+        if helm repo list | grep -q "^stable" ; then
+            helm repo remove stable
+        fi
+
+        helm repo add local http://localhost:8879/charts
+        helm plugin install https://github.com/technosophos/helm-template
+    }
 
     record_fail(){
         echo -e "\n project $1 failed: " | tee -a ${failed_log}
@@ -24,11 +54,8 @@ def build_charts = '''
     prepare_env(){
         git clone -q --depth 1 https://git.openstack.org/openstack/openstack-helm.git
         cd openstack-helm
-        source tools/gate/vars.sh
-        source tools/gate/funcs/helm.sh
-        which helm || helm_install
+        helm_install
         helm_serve
-        helm_plugin_template_install ||:
         make helm-toolkit
     }
 
@@ -36,8 +63,8 @@ def build_charts = '''
         #Some projects fail to create charts with make or don't have Makefile,
         #I want to create and upload their charts anyway:
         for i in $(ls charts | grep -v '.tgz'); do
-            helm dep up charts/$i
-            helm package charts/$i
+            helm dep up charts/${i}
+            helm package charts/${i}
         done
     }
 
@@ -51,6 +78,7 @@ def build_charts = '''
         fi
     }
 
+    set -e #will fail on any error
     WDIR=`pwd`
     job_log=${WDIR}/job.log
     failed_log=${WDIR}/failed.log
@@ -64,7 +92,7 @@ def build_charts = '''
         exit 1
     fi
     '''
-//bash script end.
+/* end of bash script. */
 
 vm(NODE_NAME,NODE_TMPL){
     stage('Project Checkout'){
